name: kitchenai
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  # Include the .env file
  assets:
    - assets/.env

